//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using HR.LeaveManagement.BlazorUI.Contracts;
using HR.LeaveManagement.BlazorUI.Providers;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;

namespace HR.LeaveManagement.BlazorUI.Pages;

public partial class Home
{
    [Inject]
    private AuthenticationStateProvider AuthenticationProvider { get;set; }

    [Inject]
    public IAuthenticationService AuthenticationService { get; set; }
    
    [Inject]
    public NavigationManager NavigationManager { get; set; }

    protected async override Task OnInitializedAsync()
    {
        await ((ApiAuthenticationProvider)AuthenticationProvider).GetAuthenticationStateAsync();
    }

    protected void GoToLogin()
    {
        NavigationManager.NavigateTo("/login");
    }

    protected void GoToRegister()
    {
        NavigationManager.NavigateTo("/register");
    }

    protected async void Logout()
    {
        await AuthenticationService.Logout();
        NavigationManager.NavigateTo("/");
    }
}
