//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using HR.LeaveManagement.BlazorUI.Contracts;
using HR.LeaveManagement.BlazorUI.Models;
using Microsoft.AspNetCore.Components;

namespace HR.LeaveManagement.BlazorUI.Pages;

public partial class Login
{
    public LoginVM Model { get; set; }
    public string Message { get; set; }

    [Inject]
    public NavigationManager NavigationManager { get; set; }
    
    [Inject]
    private IAuthenticationService AuthenticationService { get; set; }

    public Login()
    {
        
    }

    protected override void OnInitialized ()
    {
        Model = new LoginVM();
    }
    protected async Task HandleLogin()
    {
        var result = await AuthenticationService.AuthenticationAsync(Model.Email, Model.Password);
        if (result)
        {
            NavigationManager.NavigateTo("/"); // Home page if authenticated.
        }
        else
        {
            Message = "Something went wrong";
        }
    }
}
