//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using HR.LeaveManagement.BlazorUI.Contracts;
using HR.LeaveManagement.BlazorUI.Models;
using Microsoft.AspNetCore.Components;

namespace HR.LeaveManagement.BlazorUI.Pages;

public partial class Register
{
    public RegisterVM Model { get; set; }
    public string Message { get; set; }

    [Inject]
    public NavigationManager NavigationManager { get; set; }

    [Inject]
    private IAuthenticationService AuthenticationService { get; set; }

    public Register()
    {

    }
    protected override void OnInitialized()
    {
        Model = new RegisterVM();
    }

    public async void HandleRegister()
    {
        var result = await AuthenticationService.RegisterAsync
            (Model.FirstName, Model.LastName, Model.UserName, Model.Email, Model.Password);
        if (result)
        {
            NavigationManager.NavigateTo("/"); // Home page if authenticated.

        }
        else
        {
            Message = "Something went wrong";
        }
    }
}
